class AmplifFilterRegs:
    SYS_UPTIME = "SYS_UPTIME"
    SYS_REGMAP_VERSION = "SYS_REGMAP_VERSION"
    SYS_STATUS = "SYS_STATUS"
    SYS_COMMAND = "SYS_COMMAND"
    SYS_TEST = "SYS_TEST"
    SYS_IO_INPUT = "SYS_IO_INPUT"
    SYS_ERROR = "SYS_ERROR"
    SYS_TICK = "SYS_TICK"
    FACT_SERIAL_NUMBER = "FACT_SERIAL_NUMBER"
    FACT_DEVICE_ID = "FACT_DEVICE_ID"
    FACT_HW_REVISION = "FACT_HW_REVISION"
    FACT_BOOT_REVISION = "FACT_BOOT_REVISION"
    FIRM_REVISION = "FIRM_REVISION"
    FIRM_ASSEMBLY_INFO = "FIRM_ASSEMBLY_INFO"
    FIRM_APP_CHECKSUM = "FIRM_APP_CHECKSUM"
    FIRM_APP_SIZE = "FIRM_APP_SIZE"
    DBG_WRITES_CONF = "DBG_WRITES_CONF"
    CALIB_MODE = "CALIB_MODE"
    CALIB_RESERVED = "CALIB_RESERVED"
    MEAS_ENABLE = "MEAS_ENABLE"
    MEAS_MODE = "MEAS_MODE"
    MEAS_TRIGGER = "MEAS_TRIGGER"
    MEAS_RESERVED = "MEAS_RESERVED"
    MEAS_RAW = "MEAS_RAW"
    MEAS_AVERAGE = "MEAS_AVERAGE"
    MEAS_THRESHLOD = "MEAS_THRESHLOD"
    MEAS_HYSTERESIS = "MEAS_HYSTERESIS"


class MEAS_ENABLE:
    PH_EN_DISABLE = 0
    PH_EN_ENABLE = 1


class MEAS_MODE:
    MEAS_MD_RAW = 0
    MEAS_MD_FILTER = 1


class MEAS_TRIGGER:
    MEAS_TRG_NONE = 0
    MEAS_TRG_RISING = 1
    MEAS_TRG_FALLING = 2


